plugins:
  - jekyll-octicons

exclude:
  - vendor
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md

# to publish announcement / event documents with filename date in future
future: true

# to prevent jekyll build process from globbering gulp output
keep_files:
  - "assets/css"
  - "assets/js"
  - "assets/img"

collections:
  pages:
    output: true
    permalink: /:path:output_ext
  announcements:
    output: true
  events:
    output: true

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: "_events"
  values:
    layout: "event"
- scope:
    path: "_announcements"
  values:
    layout: "announcement"

page_gen:
- data: people
  template: person
  name: name_slug
  dir: people
  filter: penn_faculty_group
- data: people
  template: person
  name: name_slug
  dir: people
  filter: other_collaborators_group
