exclude:
  - vendor
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md

  # excluded by default (need to re-exclude because user _config.yml overwrites the default sequence, doesn't append to it)
  - Gemfile
  - Gemfile.lock
  - node_modules

collections:
  people:
    output: true
    permalink: /people/:name
  news:
    output: false
  events:
    output: false
  announcements:
    output: true
    permalink: /announcements/:name
  pages:
    output: true
    permalink: /:name

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: "_people"
  values:
    layout: "person"
