plugins:
  - jekyll-octicons

exclude:
  - vendor
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md
  - assets/img/originals

  # excluded by default (need to re-exclude because user _config.yml overwrites the default sequence, doesn't append to it)
  - Gemfile
  - Gemfile.lock
  - node_modules

# to publish announcement / event documents with filename date in future
future: true

collections:
  pages:
    output: true
    permalink: /:path:output_ext
  announcements:
    output: true
  events:
    output: true

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: "_events"
  values:
    layout: "event"
- scope:
    path: "_announcements"
  values:
    layout: "announcement"

page_gen:
- data: people
  template: person
  name: name_slug
  dir: people
  filter_condition: record["pcfn_group"] && record["pcfn_alum"] == false
- data: people
  template: person
  name: name_slug
  dir: people
  filter_condition: record["chatlab_group"] && record["chatlab_alum"] == false
- data: people
  template: person
  name: name_slug
  dir: people
  filter: penn_faculty_group
- data: people
  template: person
  name: name_slug
  dir: people
  filter: other_collaborators_group
