exclude:
  - vendor
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md

  # excluded by default (need to re-exclude because user _config.yml overwrites the default sequence, doesn't append to it)
  - Gemfile
  - Gemfile.lock
  - node_modules

collections:
  people:
    output: true
    permalink: /people/:name
  pages:
    output: true
    permalink: /:name

defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"
